### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [taori/NugetUnlister#4]
Hello,

It seems the new version with ReleaseFrom is not on NuGet ?

Bjorn

**Comment by taori** [comment]
Hello Bjorn,

i don't know about a ReleaseFrom method - Could you clarify please? If there is code which isn't published i'll take care of it though.

**Comment by bjorn-ali-goransson** [comment]
Sorry for being sloppy...

I was meaning to say, the version that is currently being installed if doing the `dotnet tool install --global NugetUnlister` command, does not have the command ReleaseBefore, only PrereleaseBefore.

I am referring to these additions: https://github.com/taori/NugetUnlister/commit/7081740d5c2f557955612cbe723d4e987413094c

As these additions are from August last year, and the latest released version on NuGet is from February, I believe they have not been released on nuget.org?

**Comment by taori** [comment]
After a quick look i see that you are absolutely correct. I'll scan the unit tests if the code is covered and set up CI so this doesn't happen in the future anymore. I'll probably fix this today or tomorrow. 
Thanks for reporting this.

**Comment by taori** [comment]
you can update your tool in a couple minutes and should be able to use the method which was missing in the previous release.

**Comment by taori** [comment]
@bjorn-ali-goransson the package is updated on nuget now. If you find any issues feel free to write another one.

**Comment by bjorn-ali-goransson** [comment]
Thanks for this great tool!

**Comment by taori** [comment]
@bjorn-ali-goransson You're welcome :)
